apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: rtunnell9/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: AUTH_MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000


