apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: localhost:32000/orders
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: ORDERS_MONGO_URI
            - name: NATS_URL
              value: 'http://nats-svc:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EXPIRATION_WINDOW_SECONDS
              value: '900'
            
---
apiVersion: v1
kind: Service
metadata:
  name: orders-svc
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000


