apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: rtunnell9/payments
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: JWT_KEY
            - name: MONGO_URI
              valueFrom:
                secretKeyRef: 
                  name: ticketing-secrets
                  key: PAYMENTS_MONGO_URI
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef: 
                  name: stripe-secret
                  key: STRIPE_KEY
            - name: NATS_URL
              value: 'http://nats-svc:4222'
            - name: NATS_CLUSTER_ID
              value: 'ticketing'
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
---
apiVersion: v1
kind: Service
metadata:
  name: payments-svc
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000


