name: deploy-client

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image
        run: cd client && docker build -t ${{ secrets.DOCKER_USERNAME }}/client .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/client
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - name: Configure doctl Context
        run: doctl kubernetes cluster kubeconfig save k8s-ticketing
      - name: Rollout New Deployment
        run: kubectl rollout restart deployment client-depl
